### PR TITLE
Feature/combat system

### PR DESCRIPTION
**Pull request by Quillraven**
- [x] endless loop last dungeon map folder instead of stopping at lowest level
- [x] support empty map folders
- [x] switch to CombatScreen when interacting with an enemy
- [x] add ability system
  - [x] Firebolt: single target
  - [x] Heal: self; no target
  - [x] Explosion: aoe target
- [x] update AI to use offensive/defensive spells when they have one
- [x] add Combat UI + Combat events to notify the UI to pull data from model

----

- This PR also fixes an issue with the outline shader in case an entity in range does not have a RenderComponent.
- A simple game UI is also added that shows the current dungeon level when entering a new dungeon

### CODE REVIEW

**Comment by Quillraven** [comment]
bigger refactoring of CombatSystem and Commands. The system is now executing four phases:
- start of new turn -> AI will prepare its command requests via behavior trees
- wait for player order input
- prepare commands = convert requests to real commands
- execute commands -> when all of them are finished, go back to phase 1

In addition, there is no split anymore between Command and CommandEffect like before. Now it is very similar to the Buff approach. Both classes now take a `CombatContext` as single parameter to be prepared for future changes if we need to pass additional objects to a Command or Buff. We only need to update the context now instead of each Command/Buff subclass.

In general the logic in `CombatSystem` should now be easier to follow and understand. The "core" is the `commandQueue`. As long as it is not empty the first command will be updated until it is finished. Once it is finished, it gets freed back to a pool and remove from the queue.

**Comment by Quillraven** [comment]
Another - and hopefully last- big refactoring of the combat system because a lot of other attempts failed in several ways.

The current implementation works like this:
- wait for player input for upcoming turn
- when it is available then sort entities according to their agility and add their commands to a commands "stack"
  -  for AI entities the behavior tree will be stepped to retrieve the commands
  - for a player controlled entity the command from the step above will be used
- commands are then executed one by one
- if commands get added while another command is in progress then they are added to the commands list and will be executed before any other remaining commands
  - e.g. if a death event happens then the death command is added to the commands list and will be executed right after the current command is done
  - the logic happens in `onEvent` of the `CombatSystem`. I am not sure if there is a better solution for that but this was the only way I could come up with to realize "command chaining" like:
  Entity attacks three other entities. Two of them explode like a Bomber in FF8 and the other one dies. The Bomber kills the original attacking entity.
  With the current implementation "response" commands are executed in the order they appear. This should give a good result in hopefully all the cases of QuillyCrawler ;)
- whenever a `DeathEvent` occurs then victory/defeat conditions are checked
- when all commands of the turn are executed then the turn is over and we go back to step 1
  
----

What is currently **not** supported is that the same command type of the same entity appears multiple times. This means that e.g. an attack command of one entity can only happen once per turn. 
The reason is that commands are taken out of the `availableCommands` map of the `CombatComponent`. 
Supporting this feature should not be difficult though. We only need to "clone" the command which could be e.g. done in the `onEvent` function of the `CombatSystem`. The `CombatCommandAddedEvent` needs the type of the command and the targets and then it should already work.

**Comment by Quillraven** [comment]
Making progress on the UI part. What is still missing:
- [x] Mana info update
- [x] Victory Popup
- [x] Defeat Popup
- [x] Target selection if ability requires a selectable target
- [x] Damage floating text
- [x] Do not allow selection of abilities if mana is not sufficient
- [x] Heal floating text
- [x] Consumable item logic
- [x] Buff row below entity to indicate current buffs via an icon

----

@czyzby: Can you please have a look at following scene2d custom widget? I tried to follow the documentation of LibKTX but not 100% sure if I did everything according to best practices:

```kotlin
/**
 * Style for [Bar] widget
 */
data class BarStyle(
  val frame: Drawable,
  val bar: Drawable,
  var barOffsetX: Float,
  var barOffsetY: Float
)

/**
 * Alternative widget for [ProgressBar] but since that widget never delivers the result that I expect, I created
 * this widget instead.
 * It is a [WidgetGroup] that contains a background [BarStyle.frame] image and a [BarStyle.bar] image on top of it.
 * Additionally, you can define an offset for the [bar] in pixels to correctly place it within your [frame].
 * Use [BarStyle.barOffsetX] and [BarStyle.barOffsetY] for that.
 *
 * The [bar] image can be scaled horizontally by using the [fill] function.
 */
class Bar(
  styleName: String,
  skin: Skin,
) : WidgetGroup() {
  private val style: BarStyle = skin.get(styleName, BarStyle::class.java)
  private val frame: Image = Image(style.frame)
  private val bar: Image = Image(style.bar)

  init {
    bar.setPosition(style.barOffsetX, style.barOffsetY)

    addActor(frame)
    addActor(bar)
  }

  /**
   * Scales the [bar] image horizontally by the given [percentage] value over the [scaleDuration] in seconds.
   * The minimum value for [percentage] is 0 and the maximum is 1.
   */
  fun fill(percentage: Float, scaleDuration: Float = 0.75f) {
    bar.run {
      clearActions()
      this += scaleTo(MathUtils.clamp(percentage, 0f, 1f), 1f, scaleDuration)
    }
  }

  // for whatever reason we should not multiply here by scaleX because otherwise the widget gets a left indent
  override fun getPrefWidth() = frame.drawable.minWidth

  override fun getPrefHeight() = frame.drawable.minHeight * scaleY
}

/**
 * DSL extension function to use [Bar] together with LibKTX scene2d extensions
 */
@Scene2dDsl
inline fun <S> KWidget<S>.bar(
  style: String = ktx.scene2d.defaultStyle,
  skin: Skin = Scene2DSkin.defaultSkin,
  init: Bar.(S) -> Unit = {}
): Bar = actor(Bar(style, skin), init)

/**
 * Extension function to create a [BarStyle] instance for the given [frame] and [bar].
 * Adds the new instance to the [Skin] with the given [styleName].
 * Use [block] to modify the created [BarStyle] instance.
 */
fun Skin.bar(styleName: String, frame: Drawable, bar: Drawable, block: BarStyle.() -> Unit = {}) {
  this.add(styleName, BarStyle(frame, bar, 0f, 0f).apply(block))
}
```

**Comment by czyzby** [comment]
> `skin.get(styleName, BarStyle::class.java)`

With `Skin.get` from `ktx-style`, this would become `skin[styleName]`.

You could add Kotlin contracts to ensure that the building blocks (`init`, `block`) are called once, so you can assign variables from within their scope, etc. You can see some examples of contracts usage within the KTX widget builders. Otherwise the code looks alright.

**Pull request merged**
