### PR TITLE
update gradle to 7.0, LibGDX 1.10.0 and LibKTX 1.10.0-b1

### PR DESCRIPTION
**Pull request by Quillraven**
@DRSchlaubi / @tommyettinger: do you already have experience with gradle 7.0?

I struggle to convert following lines into `libs.versions.toml`:

```
implementation("com.badlogicgames.gdx:gdx-platform:${libs.versions.gdxVersion.get()}:natives-desktop")  
implementation("com.badlogicgames.gdx:gdx-box2d-platform:${libs.versions.gdxVersion.get()}:natives-desktop") 
implementation("com.badlogicgames.gdx-controllers:gdx-controllers-desktop:${libs.versions.gdxControllersVersion.get()}")
```

I guess the problem in the first two lines is the `:natives-desktop` at the end of the version but I have no idea why it is a problem or how to fix it.

In the third line I get an error that it cannot find the dependency when using this line in `libs.versions.toml`:

```
gdx-controllers-desktop = { module = "com.badlogicgames.gdx:gdx-controllers-desktop", version.ref = "gdxControllersVersion" }
```

### CODE REVIEW

**Comment by tommyettinger** [comment]
I'm not at all sure what a libs.versions.toml file is, but it looks like it either doesn't understand .get() on a version (printing the .toString of the version property, not its value), or maybe it does understand and it only prints the reference name for some reason. Either way, I'm out of my element.

For the first two lines, it looks like classifiers aren't picked up correctly by whatever libs.versions.toml is. The `:natives-desktop` is a classifier. It could be the version not getting evaluated correctly, also.

The third line... The gdx-controllers library changed a while back, getting a ton of updates from MrStahlfelge's project. `com.badlogicgames.gdx-controllers:gdx-controllers-core:2.2.0` is the current version for core, and `com.badlogicgames.gdx-controllers:gdx-controllers-desktop:2.2.0` for desktop. If you change to those different coordinates, maybe it will find it?

Maybe try hard-coding versions for now and seeing if the errors are more reasonable?

**Comment by tommyettinger** [comment]
OK, I looked closer and saw you have the gdx-controllers dep correct already. In fact, everything seems correct, and when I cloned this PR it worked fine. 🥳 Hooray! I'm not sure if you're maybe hitting a bug in IDEA or Android Studio; my IDEA Community version is 2021.1 .

**Comment by Quillraven** [comment]
@tommyettinger thanks for your quick response! I think I explained myself poorly :)

The current version is working, you are correct. My question is how to convert the three mentioned lines to the new gradle 7.0 "catalog" syntax.

I made the controller line work but I have no idea how to convert the `:natives-desktop` lines. I found out that this is a classifier and I have no idea how to specify that in the `libs.versions.toml` file. Couldn't find anything in the official documentation: https://docs.gradle.org/current/userguide/platforms.html


Maybe you have an idea? It should be something like:
```
gdx-desktop-platform = { module = "com.badlogicgames.gdx:gdx-platform", version.ref = "gdxVersion", classifier = "natives-desktop" }
```

But they keyword `classifier`is not valid and putting it in the version part also didn't work for me :(

**Comment by tommyettinger** [comment]
I think I was able to get this to "work, kinda", but it's more verbose with version catalogs than without. https://github.com/gradle/gradle/issues/16768 may be a good place to look for more info; there is supposed to be some default value for name and maybe type, but currently they need to be specified.

lwjgl3/build.gradle.kts :

```kotlin
  implementation(libs.gdx.platform) {
    artifact {
      name = "gdx-platform"
      classifier = "natives-desktop"
      type = "jar"
    }
  }
  implementation(libs.gdx.box2d.platform) {
    artifact {
      name = "gdx-box2d-platform"
      classifier = "natives-desktop"
      type = "jar"
    }
  }
  implementation(libs.gdx.controllers.desktop)
```

gradle/libs.versions.toml (added under `[libraries]`): 

```toml
gdx-platform = { module = "com.badlogicgames.gdx:gdx-platform", version.ref = "gdxVersion" }
gdx-box2d-platform = { module = "com.badlogicgames.gdx:gdx-box2d-platform", version.ref = "gdxVersion" }
gdx-controllers-desktop = { module = "com.badlogicgames.gdx-controllers:gdx-controllers-desktop", version.ref = "gdxControllersVersion" }
```

**Comment by Quillraven** [comment]
again, thank you @tommyettinger! I think I will keep the current version for now because I agree with you that it looks more verbose with the other way. Maybe they will improve on that with upcoming releases ;)

**Pull request merged**
